name: Test 1.18.x

on:
  push:
    branches:
      - 1.18.x
  pull_request:
    branches: [ 1.18.x ]

jobs:
  main:
    runs-on: ubuntu-latest
    concurrency:
      group: run_ci-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1 # this validates gradlew
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'gradle'

    # use local gadlew
    - name: Compile
      run: ./gradlew build --no-daemon --max-workers 1
      env:
        VERSION: indev-test
    - name: Test
      run: |
          mkdir -p run/gametest
          ./gradlew runGameTestServer --no-daemon --max-workers 1
      env:
        VERSION: indev-test

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r resources/requirements.txt
    - name: Validate Resources
      run: |
        python resources validate
        python resources validate_assets
